### PR TITLE
Feat(router): Add ability to set Referrer-Policy header globally and per application.

### PR DESCRIPTION
**Pull request by mattk42**
This PR adds a new router level annotation to set the [Referrer-Policy header](https://www.w3.org/TR/referrer-policy/) default for all apps.

It also allows for a service level annotation that will override that configuration for a specific application.

### CODE REVIEW

**Comment by Cryptophobia** [comment]
Travis CI run now!

**Comment by Cryptophobia** [comment]
This will only be able to set per application or for global. Sounds like it needs to be defaulted to none to keep the existing behaviour? Can you please explain @mattk42 ?

**Comment by mattk42** [comment]
@Cryptophobia It has been a while since I made the change, but it looks to me as if when neither are set the header will not be added.

The app level config will be preferred over the router level config.

So if at the router level it is set to "strict-origin-when-cross-origin" then all apps will be given that header. But if one app has it set to "none" it will not have that header set.

I have been running from my own branch with this patch since it was pushed, but inly with a global setting at the router level.

**Comment by Cryptophobia** [comment]
@mattk42 , does it default to `none` at the global level so that we can make sure we do not break existing applications?

**Comment by Cryptophobia** [comment]
@mattk42 I did some testing and it works well. Should be completely backwards compatible unless the ReferrerPolicy security headers are being in each actual application application web servers which should be able to be migrated individually and at the discretion of the users.

Thank you for this PR.

**Pull request merged**
